# Reimagined Dots kitty defaults. Matugen updates the included colors file.

# BEGIN_QUICKSHELL_TERMINAL_FONT
font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0
# END_QUICKSHELL_TERMINAL_FONT

# BEGIN_QUICKSHELL_MATUGEN_THEME
include ~/.config/quickshell/terminal/kitty-colors.conf
# END_QUICKSHELL_MATUGEN_THEME
