#!/usr/bin/env python3
import configparser
import json
import os
import subprocess
import sys
from pathlib import Path


CONFIG_DIR = Path.home() / ".config" / "quickshell"
COLORS_PATH = CONFIG_DIR / "colors.json"
CONFIG_PATH = CONFIG_DIR / "config.json"


def load_json(path, fallback):
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception:
        return fallback


DATA = load_json(COLORS_PATH, {})
CONFIG = load_json(CONFIG_PATH, {})
MODE = CONFIG.get("themeMode") or DATA.get("mode") or "dark"
if MODE not in ("dark", "light"):
    MODE = "dark"


def color(name, mode=None, fallback="#ffffff"):
    mode = mode or MODE
    node = DATA.get("colors", {}).get(name, {})
    value = (
        node.get(mode, {})
        or node.get("default", {})
        or node.get("dark", {})
        or node.get("light", {})
        or {}
    )
    return value.get("color", fallback)


def rgba(name, mode=None, alpha="ff"):
    return f"rgba({color(name, mode).lstrip('#')}{alpha})"


def rgb_tuple(name, mode=None):
    value = color(name, mode).lstrip("#")
    if len(value) != 6:
        return (255, 255, 255)
    return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))


def rgba_css(name, mode=None, alpha="0.08"):
    r, g, b = rgb_tuple(name, mode)
    return f"rgba({r}, {g}, {b}, {alpha})"


def atomic_write(path, content):
    path = Path(path).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def append_once(path, marker, content):
    path = Path(path).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if marker in existing:
        return
    separator = "" if existing.endswith("\n") or existing == "" else "\n"
    atomic_write(path, existing + separator + content)


def run_detached(command):
    try:
        subprocess.Popen(
            command,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    except Exception:
        pass


def run_quiet(command):
    try:
        subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
    except Exception:
        pass


def wallpaper_path():
    if len(sys.argv) > 1 and sys.argv[1]:
        return sys.argv[1]
    return CONFIG.get("wallpaperPath") or ""


def write_quickshell_state():
    atomic_write(CONFIG_DIR / "primary_color.txt", color("primary"))
    atomic_write(CONFIG_DIR / "surface_color.txt", color("surface"))
    atomic_write(CONFIG_DIR / "theme_mode.txt", MODE)


def write_hyprland():
    content = f"""# Auto-generated by Quickshell Matugen pipeline
$primary = {rgba("primary")}
$primary_container = {rgba("primary_container")}
$secondary = {rgba("secondary")}
$secondary_container = {rgba("secondary_container")}
$tertiary = {rgba("tertiary")}
$surface = {rgba("surface")}
$surface_container_low = {rgba("surface_container_low")}
$surface_container = {rgba("surface_container")}
$surface_container_high = {rgba("surface_container_high")}
$outline = {rgba("outline")}
$outline_variant = {rgba("outline_variant")}
$error = {rgba("error")}
"""
    atomic_write(Path.home() / ".config" / "hypr" / "myColors.conf", content)


def write_hyprlock():
    wp = wallpaper_path()
    content = f"""# Auto-generated by Quickshell Matugen pipeline
$primary = {rgba("primary")}
$primary_container = {rgba("primary_container")}
$surface = {rgba("surface")}
$surface_container = {rgba("surface_container")}
$color_on_surface = {rgba("on_surface")}
$outline = {rgba("outline")}
$background_image = {wp}
"""
    atomic_write(Path.home() / ".config" / "hypr" / "hyprlock-colors.conf", content)


def write_kitty():
    terminal_dir = CONFIG_DIR / "terminal"
    content = f"""# Dynamic Kitty theme generated from Material You
foreground           {color("on_surface")}
background           {color("surface_container_low")}
cursor               {color("on_surface")}
selection_foreground {color("on_primary_container")}
selection_background {color("primary_container")}
url_color            {color("primary")}

active_tab_foreground      {color("on_secondary_container")}
active_tab_background      {color("secondary_container")}
inactive_tab_foreground    {color("on_surface_variant")}
inactive_tab_background    {color("surface_variant")}

active_border_color        {color("primary")}
inactive_border_color      {color("outline")}

color0               {color("surface_container_lowest", fallback=color("surface"))}
color8               {color("surface_container_highest")}
color1               {color("error")}
color9               {color("error")}
color2               {color("primary")}
color10              {color("primary")}
color3               {color("secondary")}
color11              {color("secondary")}
color4               {color("tertiary")}
color12              {color("tertiary")}
color5               {color("primary_container")}
color13              {color("primary_container")}
color6               {color("secondary_container")}
color14              {color("secondary_container")}
color7               {color("on_surface")}
color15              {color("on_surface_variant")}
"""
    atomic_write(terminal_dir / "kitty-colors.conf", content)
    atomic_write(Path.home() / ".config" / "kitty" / "colors.conf", content)
    append_once(
        Path.home() / ".config" / "kitty" / "kitty.conf",
        "# BEGIN_QUICKSHELL_MATUGEN_THEME",
        "\n# BEGIN_QUICKSHELL_MATUGEN_THEME\n"
        "include ~/.config/quickshell/terminal/kitty-colors.conf\n"
        "# END_QUICKSHELL_MATUGEN_THEME\n",
    )
    run_quiet(["killall", "-USR1", "kitty"])


def write_starship():
    content = f"""# Auto-generated by Quickshell Matugen pipeline.
add_newline = false
format = "$cmd_duration $directory$git_branch\\n  $character"

palette = "matugen"

[palettes.matugen]
primary = "{color("primary").lstrip("#")}"
on_primary = "{color("on_primary").lstrip("#")}"
secondary = "{color("secondary").lstrip("#")}"
surface = "{color("surface_container").lstrip("#")}"
surface_low = "{color("surface_container_low").lstrip("#")}"
surface_high = "{color("surface_container_high").lstrip("#")}"
on_surface = "{color("on_surface").lstrip("#")}"
on_surface_variant = "{color("on_surface_variant").lstrip("#")}"
error = "{color("error").lstrip("#")}"

[character]
success_symbol = "[›](bold fg:primary)"
error_symbol = "[›](bold fg:error)"

[directory]
home_symbol = "~"
truncation_length = 3
truncation_symbol = "../"
style = "fg:on_primary bg:primary"
format = "[ $path ]($style)"

[git_branch]
symbol = "git:"
style = "fg:on_surface bg:surface_high"
format = " [ $symbol $branch ]($style)"
truncation_length = 18
truncation_symbol = ""

[git_status]
style = "fg:secondary"
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
min_time = 800
style = "fg:on_surface_variant"
format = "[$duration]($style) "

[package]
disabled = true

[line_break]
disabled = false
"""
    atomic_write(CONFIG_DIR / "terminal" / "starship.toml", content)


def write_fish():
    content = f"""# Auto-generated by Quickshell Matugen pipeline.
set -g fish_color_normal "{color("on_surface")}"
set -g fish_color_command "{color("primary")}"
set -g fish_color_keyword "{color("primary")}"
set -g fish_color_quote "{color("secondary")}"
set -g fish_color_redirection "{color("tertiary")}"
set -g fish_color_end "{color("on_surface_variant")}"
set -g fish_color_error "{color("error")}"
set -g fish_color_param "{color("on_surface")}"
set -g fish_color_comment "{color("on_surface_variant")}"
set -g fish_color_selection --background="{color("primary_container")}"
set -g fish_color_search_match --background="{color("secondary_container")}"
set -g fish_color_operator "{color("secondary")}"
set -g fish_color_escape "{color("tertiary")}"
set -g fish_color_autosuggestion "{color("on_surface_variant")}"
set -g fish_pager_color_progress "{color("primary")}"
set -g fish_pager_color_prefix "{color("primary")}"
set -g fish_pager_color_completion "{color("on_surface")}"
set -g fish_pager_color_description "{color("on_surface_variant")}"

if status is-interactive
    if command -q starship
        set -gx STARSHIP_CONFIG "{CONFIG_DIR}/terminal/starship.toml"
        starship init fish | source
    end
end
"""
    atomic_write(Path.home() / ".config" / "fish" / "conf.d" / "quickshell-matugen.fish", content)


def write_foot():
    content = f"""# Auto-generated by Quickshell Matugen pipeline.
[colors]
foreground={color("on_surface").lstrip("#")}
background={color("surface_container_low").lstrip("#")}
regular0={color("surface_container_lowest", fallback=color("surface")).lstrip("#")}
regular1={color("error").lstrip("#")}
regular2={color("primary").lstrip("#")}
regular3={color("secondary").lstrip("#")}
regular4={color("tertiary").lstrip("#")}
regular5={color("primary_container").lstrip("#")}
regular6={color("secondary_container").lstrip("#")}
regular7={color("on_surface").lstrip("#")}
bright0={color("surface_container_highest").lstrip("#")}
bright1={color("error").lstrip("#")}
bright2={color("primary").lstrip("#")}
bright3={color("secondary").lstrip("#")}
bright4={color("tertiary").lstrip("#")}
bright5={color("primary_container").lstrip("#")}
bright6={color("secondary_container").lstrip("#")}
bright7={color("on_surface_variant").lstrip("#")}
selection-foreground={color("on_primary_container").lstrip("#")}
selection-background={color("primary_container").lstrip("#")}
"""
    atomic_write(CONFIG_DIR / "terminal" / "foot-colors.ini", content)


def write_terminal_theme():
    write_kitty()
    write_starship()
    write_fish()
    write_foot()


def gtk_css(mode):
    return f"""/*
 * GTK colors generated by Quickshell Matugen pipeline.
 */

@define-color accent_color {color("primary", mode)};
@define-color accent_fg_color {color("on_primary", mode)};
@define-color accent_bg_color {color("primary", mode)};
@define-color destructive_bg_color {color("error_container", mode)};
@define-color destructive_fg_color {color("on_error_container", mode)};
@define-color destructive_color {color("error", mode)};

@define-color window_bg_color {color("background", mode)};
@define-color window_fg_color {color("on_background", mode)};
@define-color headerbar_bg_color {color("surface_container", mode)};
@define-color headerbar_backdrop_color {color("surface_container", mode)};
@define-color headerbar_fg_color {color("on_surface", mode)};
@define-color card_bg_color {color("surface_container", mode)};
@define-color card_fg_color {color("on_surface", mode)};
@define-color sidebar_bg_color {color("background", mode)};
@define-color sidebar_fg_color {color("on_surface", mode)};
@define-color sidebar_row_active_bg_color {color("secondary_container", mode)};
@define-color sidebar_row_active_fg_color {color("on_secondary_container", mode)};
@define-color secondary_sidebar_bg_color {color("surface_container_low", mode)};
@define-color secondary_sidebar_fg_color {color("on_surface_variant", mode)};
@define-color sidebar_border_color @sidebar_bg_color;
@define-color sidebar_backdrop_color @sidebar_bg_color;
@define-color view_bg_color {color("surface_container_lowest", mode, color("surface", mode))};
@define-color view_fg_color {color("on_surface", mode)};
@define-color overview_bg_color {color("surface_container_lowest", mode, color("surface", mode))};
@define-color overview_fg_color {color("on_surface", mode)};

@define-color popover_bg_color {color("surface_container_highest", mode)};
@define-color popover_fg_color {color("on_surface", mode)};
@define-color popover_fg_hover_color {rgba_css("on_surface", mode, "0.08")};
@define-color dialog_bg_color {color("surface_container_high", mode)};
@define-color dialog_fg_color {color("on_surface", mode)};
@define-color thumbnail_bg_color {color("surface_container_high", mode)};
@define-color thumbnail_fg_color {color("on_surface", mode)};

@define-color inverse_on_surface {color("inverse_on_surface", mode)};
@define-color inverse_primary {color("inverse_primary", mode)};
@define-color inverse_surface {color("inverse_surface", mode)};
@define-color surface_container_highest {color("surface_container_highest", mode)};
@define-color surface_container_high {color("surface_container_high", mode)};
@define-color on_surface_variant {color("on_surface_variant", mode)};
@define-color surface_variant {color("surface_variant", mode)};
@define-color outline {color("outline", mode)};

* {{
  caret-color: @accent_color;
}}

window {{
  background: @window_bg_color;
  color: @window_fg_color;
}}

.text-button,
.popup-menu-item {{
  border-radius: 999px;
}}
"""


def write_gtk_settings(path):
    path = Path(path).expanduser()
    parser = configparser.ConfigParser()
    if path.exists():
        parser.read(path)
    if "Settings" not in parser:
        parser["Settings"] = {}
    parser["Settings"]["gtk-application-prefer-dark-theme"] = "1" if MODE == "dark" else "0"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        parser.write(handle, space_around_delimiters=False)


def write_gtk():
    atomic_write(Path.home() / ".config" / "gtk-3.0" / "gtk.css", gtk_css(MODE))
    atomic_write(
        Path.home() / ".config" / "gtk-4.0" / "gtk.css",
        "@media (prefers-color-scheme: light) {\n"
        + gtk_css("light")
        + "\n}\n\n@media (prefers-color-scheme: dark) {\n"
        + gtk_css("dark")
        + "\n}\n",
    )
    write_gtk_settings(Path.home() / ".config" / "gtk-3.0" / "settings.ini")
    write_gtk_settings(Path.home() / ".config" / "gtk-4.0" / "settings.ini")

    scheme = "prefer-dark" if MODE == "dark" else "prefer-light"
    run_quiet(["gsettings", "set", "org.gnome.desktop.interface", "color-scheme", scheme])


def apply_kde():
    primary = color("primary")
    if not primary:
        return
    mode_flag = "-d" if MODE == "dark" else "-l"
    run_detached(["kde-material-you-colors", mode_flag, "--color", primary, "-sv", "5"])


def reload_shell_bits():
    run_quiet(["hyprctl", "reload"])


def main():
    if not DATA:
        print("colors.json not found or invalid", file=sys.stderr)
        return 1

    write_quickshell_state()
    write_hyprland()
    write_hyprlock()
    write_terminal_theme()
    write_gtk()
    apply_kde()
    reload_shell_bits()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
